Repository SouJunior/vagas-api, pull requests merged in 2023-06, with the labels that each got.

#117 feat: upload company and created new variables
  src/database/entities/companies.entity.ts
  src/modules/company/company.controller.ts
  src/modules/company/company.module.ts
  src/modules/company/dtos/update-company.dto.ts
  src/modules/company/dtos/update-company.sto.ts
  src/modules/company/enum/company-size.enum.ts
  src/modules/company/repository/company-repository.ts
  src/modules/company/services/update-company.service.ts
  src/modules/upload/upload.module.ts
Labels: Feature

#118 fix: include auth guard and bearer auth
  src/modules/company/company.controller.ts
Labels: Feature

#119 fix(company): resolve when file is send
  README.md
  src/modules/company/company.controller.ts
  src/modules/company/company.module.ts
  src/modules/company/dtos/update-company.dto.ts
  src/modules/company/repository/company-repository.ts
  src/modules/company/services/update-company.service.ts
Labels: bug, Backend

#121 Main
  src/database/entities/applications.entity.ts
  src/database/entities/curriculum.entity.ts
  src/database/entities/users.entity.ts
Labels: enhancement, Feature, Backend

#122 feat: insert api properity in update company for swagger
  src/modules/company/dtos/update-company.dto.ts
Labels: Feature

#124 fix: update name variable for new rules
  src/database/entities/companies.entity.ts
  src/modules/company/dtos/update-company.dto.ts
Labels: enhancement
