Repository SouJunior/vagas-api, pull requests merged in 2023-04, with the labels that each got.

#95 adiciona uma melhor abordagem para deploy local, servidor e push para o docker registry
  .github/workflows/docker-image-merge.yml
  .github/workflows/docker-image.yml
  docker-compose-vm.yml
  run
Labels: enhancement, Feature

#99 Ignora alterações no readme.md
  .github/workflows/docker-image-merge.yml
  .github/workflows/docker-image.yml
Labels: enhancement

#101 add new router to get all jobs from logged company
  README.md
  src/app.module.ts
  src/modules/auth/decorator/logged-admin.decorator.ts
  src/modules/jobs/jobs.controller.ts
  src/modules/user/dtos/get-by-params.dto.ts
  src/modules/user/user.controller.ts
  src/shared/Swagger/unprocessable-entity.swagger.ts
  src/shared/Swagger/user/create-response.swagger.ts
  src/shared/Swagger/user/list-response.swagger.ts
  src/shared/Swagger/user/recovery-password.swagger.ts
Labels: Feature

#102 Refactor create job dto and entity
  src/app.module.ts
  src/database/entities/jobs.entity.ts
  src/modules/jobs/dtos/create-job.dto.ts
Labels: Refactor

#105 fix deploy
  src/database/entities/jobs.entity.ts
  src/modules/jobs/dtos/create-job.dto.ts
  src/modules/jobs/services/get-all-jobs.service.ts
Labels: bug, Backend

#106 fix: pagination
  src/database/entities/jobs.entity.ts
  src/modules/company/repository/company-repository.ts
  src/modules/jobs/repository/job.resository.ts
  src/modules/user/repository/user.repository.ts
  src/shared/pagination/pageOptions.dto.ts
Labels: bug, Backend

#107 feat: add pwd in enum
  src/database/entities/jobs.entity.ts
  src/modules/jobs/dtos/create-job.dto.ts
  src/modules/jobs/enums/job-affirmative-type.enum.ts
Labels: enhancement, Feature

#112 fix: create jobs dto
  src/app.module.ts
  src/modules/auth/dtos/user-login.dto.ts
  src/modules/company/dtos/create-company.dto.ts
  src/modules/jobs/dtos/create-job.dto.ts
  src/modules/jobs/jobs.controller.ts
  src/modules/user/dtos/create-user.dto.ts
Labels: bug, Backend

#113 feat: upload file
  package-lock.json
  package.json
  src/app.module.ts
  src/main.ts
  src/modules/upload/types/response-s3.types.ts
  src/modules/upload/upload.controller.ts
  src/modules/upload/upload.module.ts
  src/modules/upload/upload.service.ts
Labels: enhancement, Feature, Backend, squad akamaru - perfil, squad cereal killers - vagas
