Repository SouJunior/vagas-api, pull requests merged in 2023-10, with the labels that each got.

#145 Main
  src/modules/mails/templates/confirmEmailCompany.hbs
  src/modules/mails/templates/confirmEmailUser.hbs
Labels: enhancement, hacktoberfest

#146 Atualização da função que valida o cpf e cnpj
  package-lock.json
  package.json
  src/modules/upload/upload.controller.ts
  src/modules/user/user.controller.ts
  src/shared/validators/cnpj.validator.ts
Labels: documentation, enhancement, hacktoberfest, Refactor

#147 Criação de vagas
  src/modules/jobs/dtos/create-job.dto.ts
  src/modules/jobs/services/create-job.service.ts
Labels: enhancement, hacktoberfest, Refactor

#148 feat: set catch in db calls
  src/modules/applications/applications.controller.ts
  src/modules/applications/repository/applications.repository.ts
  src/modules/auth/auth.controller.ts
  src/modules/company/company.controller.ts
  src/modules/company/dtos/decorators/match.decorator.ts
  src/modules/company/dtos/update-my-password.dto.ts
  src/modules/company/repository/company-repository.ts
  src/modules/jobs/jobs.controller.ts
  src/modules/jobs/repository/job.repository.ts
  src/modules/mails/mail.module.ts
  src/modules/user/decorators/match.decorator.ts
  src/modules/user/dtos/update-my-password.dto.ts
  src/modules/user/repository/user.repository.ts
  src/modules/user/services/find-one-user.service.ts
  src/shared/Swagger/decorators/auth/login.swagger.ts
  src/shared/Swagger/decorators/auth/user-logged.swagger.ts
  src/shared/Swagger/decorators/comment/create-comment.swagger.ts
  src/shared/Swagger/decorators/comment/delete-commentary.swagger.ts
  src/shared/Swagger/decorators/comment/get-all-commentaries.swagger.ts
  src/shared/Swagger/decorators/comment/get-one-commentary.swagger.ts
  src/shared/Swagger/decorators/comment/update-commentary.swagger.ts
  src/shared/Swagger/decorators/company/activate-company.swagger.ts
  src/shared/Swagger/decorators/company/create-company.swagger.ts
  src/shared/Swagger/decorators/company/delete-company-by-id.swagger.ts
  src/shared/Swagger/decorators/company/get-all-companies.swagger.ts
  src/shared/Swagger/decorators/company/get-company-by-id.swagger.ts
  src/shared/Swagger/decorators/company/recovery-password-by-email.swagger.ts
  src/shared/Swagger/decorators/company/update-company-by-id.swagger.ts
  src/shared/Swagger/decorators/company/update-password-after-recovery-email.swagger.ts
  src/shared/Swagger/decorators/company/update-password.swagger.ts
  src/shared/Swagger/decorators/curriculum/upload-curriculum.swagger.ts
  src/shared/Swagger/decorators/jobs/archive-job.swagger.ts
  src/shared/Swagger/decorators/jobs/create-new-job.swagger.ts
  src/shared/Swagger/decorators/jobs/get-all-jobs-of-logged-company.swagger copy.ts
  src/shared/Swagger/decorators/jobs/get-all-jobs-of-logged-company.swagger.ts
  src/shared/Swagger/decorators/jobs/get-one-job.swagger.ts
  src/shared/Swagger/decorators/jobs/search-job.swagger.ts
  src/shared/Swagger/decorators/jobs/update-job.swagger.ts
  src/shared/Swagger/decorators/reports/create-report.swagger.ts
  src/shared/Swagger/decorators/reports/delete-report.swagger.ts
  src/shared/Swagger/decorators/reports/get-all-reports.swagger.ts
  src/shared/Swagger/decorators/reports/get-report-by-id.swagger.ts
  src/shared/Swagger/decorators/reports/update-report.swagger.ts
  src/shared/Swagger/decorators/upload/upload.swagger.ts
  src/shared/Swagger/decorators/user/classes/create-response.swagger.ts
  src/shared/Swagger/decorators/user/classes/list-response.swagger.ts
  src/shared/Swagger/decorators/user/classes/recovery-password.swagger.ts
  src/shared/Swagger/decorators/user/delete-user.swagger.decorator.ts
  src/shared/Swagger/decorators/user/get-user-adm.swagger.decorator.ts
  src/shared/Swagger/decorators/user/get-user.swagger.decorator.ts
  src/shared/Swagger/decorators/user/recover-by-email.swagger.decorator.ts
  src/shared/Swagger/decorators/user/update-pass-after-email-recovery.swagger.decorator.ts
  src/shared/Swagger/decorators/user/update-password.swagger.decorator.ts
  src/shared/Swagger/decorators/user/update-user.swagger.decorator.ts
  src/shared/Swagger/decorators/user/view-users.swagger.decorator.ts
Labels: documentation, enhancement, hacktoberfest, Feature, Refactor

#149 Atualização do Swagger para editar as empresas
  src/modules/auth/dtos/user-login.dto.ts
  src/modules/company/dtos/update-company.dto.ts
  src/shared/Swagger/decorators/company/update-company-by-id.swagger.ts
Labels: documentation

#151 refactor: update dto
  src/modules/applications/dtos/data-application.dto.ts
  src/modules/auth/dtos/user-login-response.dto.ts
  src/modules/comment/dtos/update-comment.dto.ts
Labels: Refactor

#152 refactor: comments and company dto
  src/modules/comment/dtos/comment-id.dto.ts
  src/modules/comment/dtos/create-comment.dto.ts
  src/modules/company/dtos/company-id.dto.ts
Labels: Refactor

#153 refactor company
  src/modules/company/dtos/create-company.dto.ts
  src/modules/company/dtos/update-company.dto.ts
  src/modules/company/dtos/update-my-password.dto.ts
Labels: Refactor
